import Navbar from "../components/Navbar";
import "./globals.css";
import ToastProvier from "@/components/ToastProvier";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ToastProvier>{children}</ToastProvier>
      </body>
    </html>
  );
}
